### ISSUE TITLE
Switch to Typescript and Vercel (For Deployment) 

### ISSUE THREAD

**Issue by raghav0622** [netizener/OctoMov#8]
Switch to Typescript, Vercel (For Deployment) and Preact for development?

**Comment by netizener** [comment]
I don't have practical experience for those technologies atm. Maybe fork the repo and show me any significant advantages I might have if I chose that stack instead?

**Comment by raghav0622** [comment]
> I don't have practical experience for those technologies atm. Maybe fork the repo and show me any significant advantages I might have if I chose that stack instead?

ok
